services:
  api:
    build: .
    ports:
      - "4545:4545"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SERVICE=api

  bot:
    build: .
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_URL=http://api:4545
      - SERVICE=bot
    depends_on:
      - api 